<MyRoot>:

    random_label: random_label
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "CodeStuff"
            font_size: 50
            color: 0.92, 0.45, 0

        Label:
            id: random_label
            text: "-"
            font_size: 64


        Button:
            text: "Generate"
            font_size: 70
            on_press: root.gen_numb()

        

